[build]
  command = "npm run build"
  publish = "dist"

to = "https://easygoing-analysis-production.up.railway.app/api/:splat"
  from = "/api/*"
  to = "https://easygoing-analysis-production.up.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
